"use client"
import { HeroParallax } from "../Ui/HeroParallel"

export default function HeroParallaxDemo() {
  return <HeroParallax socialMediaPosts={socialMediaPosts} />
}
export const socialMediaPosts = [
  {
    type: "instagram",
    username: "designstudio",
    avatar: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=400&width=400",
    likes: 1234,
    caption: "Just finished this amazing project! 🎨✨",
    timeAgo: "2h",
  },
  {
    type: "twitter",
    username: "techguru",
    handle: "@techguru",
    avatar: "/placeholder.svg?height=40&width=40",
    content:
      "The future of web development is here! Excited to share our latest innovations in AI-powered design tools. 🚀",
    likes: 892,
    retweets: 234,
    timeAgo: "4h",
  },
  {
    type: "linkedin",
    username: "Sarah Johnson",
    title: "Senior Product Manager",
    avatar: "/placeholder.svg?height=40&width=40",
    content:
      "Thrilled to announce our team's latest achievement in user experience design. This project showcases the power of collaborative innovation.",
    likes: 567,
    comments: 89,
    timeAgo: "1d",
  },
  {
    type: "instagram",
    username: "creativecode",
    avatar: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=400&width=400",
    likes: 2156,
    caption: "Late night coding sessions hit different ⚡",
    timeAgo: "6h",
  },
  {
    type: "twitter",
    username: "uxdesigner",
    handle: "@uxdesigner",
    avatar: "/placeholder.svg?height=40&width=40",
    content:
      "Hot take: The best designs are invisible. Users should never have to think about how to use your product. Simplicity wins every time. 💡",
    likes: 1456,
    retweets: 678,
    timeAgo: "8h",
  },
  {
    type: "facebook",
    username: "Innovation Hub",
    avatar: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=300&width=500",
    content:
      "Our team is growing! We're looking for passionate developers and designers to join our mission of creating amazing digital experiences.",
    likes: 234,
    comments: 45,
    shares: 12,
    timeAgo: "12h",
  },
  {
    type: "instagram",
    username: "webdev_daily",
    avatar: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=400&width=400",
    likes: 3421,
    caption: "Responsive design is not optional in 2024 📱💻",
    timeAgo: "1d",
  },
  {
    type: "twitter",
    username: "startuplife",
    handle: "@startuplife",
    avatar: "/placeholder.svg?height=40&width=40",
    content:
      "Building a startup is like solving a puzzle where the pieces keep changing shape. Embrace the chaos and keep iterating! 🧩",
    likes: 789,
    retweets: 156,
    timeAgo: "2d",
  },
  {
    type: "linkedin",
    username: "Michael Chen",
    title: "Full Stack Developer",
    avatar: "/placeholder.svg?height=40&width=40",
    content:
      "Just deployed our new microservices architecture. The performance improvements are incredible - 40% faster load times!",
    likes: 892,
    comments: 134,
    timeAgo: "3d",
  },
  {
    type: "instagram",
    username: "design_inspiration",
    avatar: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=400&width=400",
    likes: 5678,
    caption: "Less is more. Clean, minimal interfaces that users love 🎯",
    timeAgo: "2d",
  },
  {
    type: "twitter",
    username: "airesearcher",
    handle: "@airesearcher",
    avatar: "/placeholder.svg?height=40&width=40",
    content:
      "The intersection of AI and creativity is where magic happens. We're not replacing human creativity, we're amplifying it. 🤖✨",
    likes: 2134,
    retweets: 567,
    timeAgo: "1d",
  },
  {
    type: "facebook",
    username: "Tech Community",
    avatar: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=300&width=500",
    content:
      "Amazing turnout at yesterday's developer meetup! The energy and passion in our community is incredible. Already planning the next event!",
    likes: 456,
    comments: 78,
    shares: 23,
    timeAgo: "1d",
  },
  {
    type: "linkedin",
    username: "Emma Rodriguez",
    title: "UX Research Lead",
    avatar: "/placeholder.svg?height=40&width=40",
    content:
      "User research isn't just about asking questions - it's about listening to what users don't say. The insights are often in the pauses and hesitations.",
    likes: 1234,
    comments: 89,
    timeAgo: "4d",
  },
  {
    type: "instagram",
    username: "frontend_magic",
    avatar: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=400&width=400",
    likes: 4321,
    caption: "CSS animations that make users smile 😊 Details matter!",
    timeAgo: "3d",
  },
  {
    type: "twitter",
    username: "productmanager",
    handle: "@productmanager",
    avatar: "/placeholder.svg?height=40&width=40",
    content:
      "Shipping is a feature. The best product that never launches is worthless. Sometimes good enough today beats perfect tomorrow. 🚢",
    likes: 1678,
    retweets: 234,
    timeAgo: "5d",
  },
  {
    type: "instagram",
    username: "mobile_first",
    avatar: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=400&width=400",
    likes: 2890,
    caption: "Mobile-first design principles in action 📱✨",
    timeAgo: "1d",
  },
  {
    type: "linkedin",
    username: "Alex Thompson",
    title: "DevOps Engineer",
    avatar: "/placeholder.svg?height=40&width=40",
    content:
      "Automated our entire deployment pipeline today. From code commit to production in under 5 minutes. The future is now! 🚀",
    likes: 756,
    comments: 92,
    timeAgo: "2d",
  },
  {
    type: "twitter",
    username: "cloudnative",
    handle: "@cloudnative",
    avatar: "/placeholder.svg?height=40&width=40",
    content: "Kubernetes isn't just a tool, it's a mindset. Think distributed, think scalable, think resilient. 🌐",
    likes: 1123,
    retweets: 445,
    timeAgo: "3d",
  },
  {
    type: "facebook",
    username: "Design Collective",
    avatar: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=300&width=500",
    content:
      "Celebrating 5 years of creative collaboration! Thank you to our amazing community of designers and developers.",
    likes: 892,
    comments: 156,
    shares: 67,
    timeAgo: "2d",
  },
  {
    type: "instagram",
    username: "code_aesthetics",
    avatar: "/placeholder.svg?height=40&width=40",
    image: "/placeholder.svg?height=400&width=400",
    likes: 3567,
    caption: "Beautiful code is readable code 📖✨",
    timeAgo: "4d",
  },
]
